export const projects = [
  {
    id: "rainforest-guard",
    name: "Rainforest Guard REDD+",
    location: "Acre, Brazil",
    category: "forestry",
    methodology: "REDD+",
    price: 8.5,
    available: 120000,
    image: "/rainforest-project.jpg",
    description:
      "Avoided deforestation initiative combining satellite + on-ground IoT for leakage tracking. Automated issuance via AI thresholds.",
  },
  {
    id: "wind-west",
    name: "Wind Power West",
    location: "Gujarat, India",
    category: "renewable",
    methodology: "Gold Standard",
    price: 6.2,
    available: 90000,
    image: "/wind-turbines-field.png",
    description: "Grid-connected wind farm delivering renewable electricity and verifiable emission reductions.",
  },
  {
    id: "landfill-methane",
    name: "Landfill Methane Capture",
    location: "Hanoi, Vietnam",
    category: "methane",
    methodology: "VCS",
    price: 7.1,
    available: 45000,
    image: "/landfill-methane.jpg",
    description: "Flares and energy recovery reduce methane leakage with continuous IoT monitoring.",
  },
  {
    id: "mangrove-blue",
    name: "Mangrove Restoration",
    location: "Kisumu, Kenya",
    category: "forestry",
    methodology: "Blue Carbon",
    price: 12.0,
    available: 38000,
    image: "/mangrove-restoration.jpg",
    description: "Coastal restoration for high permanence and biodiversity co-benefits.",
  },
  {
    id: "solar-sunrise",
    name: "Solar Sunrise Park",
    location: "Nevada, USA",
    category: "renewable",
    methodology: "Gold Standard",
    price: 5.8,
    available: 150000,
    image: "/expansive-solar-farm.png",
    description: "Utility-scale solar farm with transparent grid metering data feeds.",
  },
  {
    id: "cookstove-clean",
    name: "Clean Cookstoves",
    location: "Kigali, Rwanda",
    category: "methane",
    methodology: "VCS",
    price: 4.9,
    available: 72000,
    image: "/cookstove-project.jpg",
    description: "Efficient stoves reduce biomass usage and indoor air pollution, tracked via field sensors.",
  },
]
